"""Add nullable in non necessary column add new column basee

Revision ID: 8e6cf710ae6e
Revises: d9bb329596e6
Create Date: 2025-10-25 00:33:20.810647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e6cf710ae6e'
down_revision: Union[str, Sequence[str], None] = 'd9bb329596e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('users', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'createdAt')
    op.drop_column('search_history', 'createdAt')
    # ### end Alembic commands ###
