"""Added search history entity

Revision ID: c64680d1d99b
Revises: 07afdf842664
Create Date: 2025-10-19 13:28:56.685534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c64680d1d99b'
down_revision: Union[str, Sequence[str], None] = '07afdf842664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requestedAt', sa.DateTime(), nullable=True),
    sa.Column('requestedIp', sa.String(length=100), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'data_search')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_search', mysql.VARCHAR(length=1000), nullable=False))
    op.drop_table('search_history')
    # ### end Alembic commands ###
