"""add user find content column

Revision ID: d9bb329596e6
Revises: c64680d1d99b
Create Date: 2025-10-24 22:53:45.776590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bb329596e6'
down_revision: Union[str, Sequence[str], None] = 'c64680d1d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('content', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'content')
    # ### end Alembic commands ###
